### ISSUE TITLE
array lookup using cint index

### ISSUE THREAD

**Issue by n1v0lg** [bristolcrypto/SPDZ-2#1]
There appears to be some inconsistency in the array lookup functionality.

Given an array of sints and a cint index, using the index to access an element in the array produces a 0 value instead of the actual element stored at the index. Meanwhile this works just fine when an array of cints is used or when the lookup is done via a linear scan across the sint array. Below are several code snippets to reproduce the issue (also attached).

Correct lookups vs. incorrect lookups:

``` python
from Compiler import types

def contrived_lookup(a, idx):
    acc = 0
    for i in range(len(a)):
        acc += (idx == i) * a[i]
    return acc

array_type = sint
secret_array = types.Array(10, array_type)
for i in range(10):
    secret_array[i] = array_type(i)

for i in range(10):
    print_ln("secret_array[%s]: %s", i, secret_array[i].reveal())

idx = cint(5)
val = contrived_lookup(secret_array, idx)
print_ln("This works: secret_array[%s]: %s", 
         idx, val.reveal())

clear_array = types.Array(10, cint)
for i in range(10):
    clear_array[i] = cint(i)
print_ln("This also works: clear_array[%s]: %s", 
         idx, clear_array[idx])

val = secret_array[idx]
print_ln("This is broken: secret_array[%s]: %s", 
         idx, val.reveal())
```

Another related issue is demonstrated below. When the lookup is done on a sint array first and subsequently on a cint array, neither lookup works correctly (both produce 0 values).

``` python
from Compiler import types

secret_array = types.Array(10, sint)
for i in range(10):
    secret_array[i] = sint(i)

for i in range(10):
    print_ln("secret_array[%s]: %s", i, secret_array[i].reveal())

new_idx = cint(5)
print_ln("This is broken: secret_array[%s]: %s", 
         new_idx, secret_array[new_idx].reveal())

clear_array = types.Array(10, cint)
for i in range(10):
    clear_array[i] = cint(i)

for i in range(10):
    print_ln("clear_array[%s]: %s", i, clear_array[i])

idx = cint(5)
print_ln("This is now also broken: clear_array[%s]: %s", 
             idx, clear_array[idx])
```

Attached: 
[lookup_issues.zip](https://github.com/bristolcrypto/SPDZ-2/files/467900/lookup_issues.zip)

**Comment by mkskeller** [comment]
This should be fixed by using -M when compiling. However, there was bug that is now fixed.
