### ISSUE TITLE
Vickrey error

### ISSUE THREAD

**Issue by prvsousa** [bristolcrypto/SPDZ-2#10]
When I'm trying to execute the vickrey as an example:

I got:
 ```
loading params from: Player-Data/2-128-40/Params-Data
terminate called after throwing an instance of 'file_error'
  what():  File Error : Player-Data/2-128-40/Params-Data
```

**Comment by mkskeller** [comment]
You have to run Script/setup-online.sh first.

**Comment by prvsousa** [comment]
I run this but I get the same error.

**Comment by mkskeller** [comment]
Are you running all program from the same directory?

**Comment by prvsousa** [comment]
```
both parties' online phase:

./Player-Online.x -pn 5000 0 tutorial

./Player-Online.x -pn 5000 1 tutorial (in a separate terminal)
```

**Comment by prvsousa** [comment]
ok, instead of tutorial -> vickrey

**Comment by mkskeller** [comment]
The setup script as well? After you run the setup script, there should by Player-Data/Params-Data in the directory that you run Player-Online.x from.

**Comment by prvsousa** [comment]
Yes. You can see the sequence of the commands:

> 191  Scripts/setup-online.sh
>  9192  ./compile.py vickrey
>  9194* ./Server.x 2 5000 &
>  9195* ./Player-Online.x -pn 5000 0 vickrey 
>  9196  ./Player-Online.x -pn 5000 1 vickrey

**Comment by prvsousa** [comment]
I also tried to add a new simple program that only makes an addition and the same error occurs.

**Comment by prvsousa** [comment]
My error was solved with generating of 2-128-40.
