### ISSUE TITLE
Does SPDZ support array operations?

### ISSUE THREAD

**Issue by xiaolixiaoyi** [bristolcrypto/SPDZ-2#12]
I want to test the throughput of SPDZ, but I find that the following code does not work:
```
a = Array(100, sint)
b = Array(100, sint)
# assign values to a and b
c = a * b # raise an error
```
I know we can perform element-wise multiplications with a for-loop, but it will make the multiplications run sequentially. Is there any way to make the independent multiplications above run parallelly?

**Comment by mkskeller** [comment]
Python loops will be unrolled at compile time:
```
for i in range(100):
    c[i] = a[i] * b[i]
```

**Comment by xiaolixiaoyi** [comment]
Thanks.
I wanted to assign some values to an Array:
```
n = 10
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
A = Array(n, sfix)

start_timer(1)
@for_range(n)
def f(i):
    A[i] = sfix(arr[i])
stop_timer(1)
```
But it raised an error while compiling:
```
Traceback (most recent call last):
  File "./compile.py", line 87, in <module>
    main()
  File "./compile.py", line 84, in main
    compilation()
  File "./compile.py", line 71, in compilation
    assemblymode=options.assemblymode, debug=options.debug)
  File "/root/spdz/Compiler/compilerLib.py", line 55, in run
    execfile(prog.infile, VARS)
  File "/root/spdz/Programs/Source/test.mpc", line 15, in <module>
    @for_range(n)
  File "/root/spdz/Compiler/library.py", line 818, in decorator
    range_loop(loop_body, start, stop, step)
  File "/root/spdz/Compiler/library.py", line 808, in range_loop
    while_loop(loop_fn, condition, start)
  File "/root/spdz/Compiler/library.py", line 982, in while_loop
    if_statement(pre_condition, lambda: do_while(loop_fn))
  File "/root/spdz/Compiler/library.py", line 1071, in if_statement
    if_fn()
  File "/root/spdz/Compiler/library.py", line 982, in <lambda>
    if_statement(pre_condition, lambda: do_while(loop_fn))
  File "/root/spdz/Compiler/library.py", line 1011, in do_while
    condition = loop_fn()
  File "/root/spdz/Compiler/library.py", line 979, in loop_fn
    result = loop_body(regint.pop())
  File "/root/spdz/Compiler/library.py", line 796, in loop_fn
    loop_body(i)
  File "/root/spdz/Programs/Source/test.mpc", line 17, in f
    A[i] = sfix(arr[i])
TypeError: list indices must be integers, not regint
```
I know I can do it with a for-loop, but it costs much time to compile, especially when there are comparisons.
So is there any efficient way to assign arr to A with '@for_range'?

**Comment by rdragos** [comment]
You cannot access python lists inside @for_range loops.
I recommend you to do the initialization using a python for loop and then manipulate the SPDZ array using @for_range constructs.

**Comment by lilir5** [comment]
Hi all,
I have the same issue when trying to use list inside @for_range loops. Could you please explain with more details. I really appreciate that.
Thanks

**Comment by mkskeller** [comment]
As Dragos said, you cannot do that, but can populate an Array with a Python for loop.

**Comment by mkskeller** [comment]
Example:
```
inputs = [1,2,3]
a = Array(len(inputs), sint)
for i in range(len(inputs)):
    a[i] = inputs[i]
```

**Comment by lilir5** [comment]
Thank you Marcel. The problem is, when I use for loop with big vector in my program, it takes ages to compile, so I need to use @for_range. Is there any way to use list in @for_range? How can I manipulate the SPDZ code to do so?Or which part should be changed? 
Thank you very much

**Comment by mkskeller** [comment]
If you really need to use @for_range, you can try using public_input(), which reads number by number from Player-Data/Public-Input.
