### ISSUE TITLE
Change dependencies of Loopback (to use with multiple devices)

### ISSUE THREAD

**Issue by prvsousa** [bristolcrypto/SPDZ-2#14]
Hi. 

I has trying to create a real environment to process the multiparty computation, but I'm facing issues based in the use of localhost, have you some idea regarding how to perform this change? For an interface, for example, wlp2s0?

Thanks.

**Comment by prvsousa** [comment]
I did not explain clearly.

My problem is that I need to use specific IP I can't use DNS for now. Or just in boarder line run a local DNS to atribute a name to my local machines.

Is there a way to make this with IP I know the "-h" but that just work with DNS
best

**Comment by mkskeller** [comment]
The online phase is hard-coded to use hostnames, but you can replace the following line in `Machine.cpp`:
```N.init(my_number,PortnumBase,hostname.c_str());```
by something like
```N.init(my_number, nplayers, PortnumBase, "HOSTS");```
(similar to `TripleMachine.cpp`). This will read `nplayer` hostnames or IPs from the file `HOSTS`.

**Comment by prvsousa** [comment]
Ok thanks!

**Comment by prvsousa** [comment]
Only one question, I'm making this and it's working for two of my PC's. But between other PC I'm with problems with error:
```

terminate called after throwing an instance of 'mac_fail'
  what():  MacCheck Failure
```

Can you explain me in what situations this error throw? This way, I can evaluate what I'm doing wrong. Thanks!

**Comment by mkskeller** [comment]
This is a catch all meaning that a party hasn't followed the protocol properly. Usually this happens if something with the preprocessed information has gone wrong, so the first thing to try is to call `make clean` and remove `Player-Data`, and the compiling and setting up again.
