### ISSUE TITLE
Bug in @for_range loops

### ISSUE THREAD

**Issue by ocalex86** [bristolcrypto/SPDZ-2#15]
The following minimal .mpc with a @for_range loop iterates forever instead of only 4 times. Note that if compiled with the -n option, everything goes fine. 
```k= 3
vec = Array(k, sint)
@for_range(4)
def h(i):
    print_ln("iteration: %s ", i)
    vec[0].reveal()
    @for_range(k)
    def f(j):
        vec[j] = sint(0)

**Comment by mkskeller** [comment]
Should be fixed now.
