### ISSUE TITLE
Unable to compile on MAC OS X Yosemite

### ISSUE THREAD

**Issue by GiuliaDro** [bristolcrypto/SPDZ-2#17]
I followed your instructions but I have an issue compiling SPDZ.
I used the default CONFIG. 
Can you kindly help?

$ make
g++   -g -Wextra -Wall -O3 -I. -pthread      '-DPREP_DIR="Player-Data/"' -maes -mpclmul -msse4.1 -mtune=native  -c -o Math/Setup.o Math/Setup.cpp
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:9:
In file included from ./Math/gf2n.h:12:
In file included from ./Tools/random.h:8:
./Tools/aes.h:53:16: warning: unknown attribute 'optimize' ignored
      [-Wunknown-attributes]
__attribute__((optimize("unroll-loops")))
               ^
./Tools/aes.h:65:16: warning: unknown attribute 'optimize' ignored
      [-Wunknown-attributes]
__attribute__((optimize("unroll-loops")))
               ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:9:
In file included from ./Math/gf2n.h:14:
./Math/gf2nlong.h:109:37: error: invalid use of member 'a' in static member
      function
  static int size() { return sizeof(a); }
                                    ^
./Math/gf2nlong.h:116:34: error: use of undeclared identifier
      '_mm_cvtsi128_si64x'; did you mean '_mm_cvtsi128_si64'?
  word get_word() const { return _mm_cvtsi128_si64x(a.a); }
                                 ^~~~~~~~~~~~~~~~~~
                                 _mm_cvtsi128_si64
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/emmintrin.h:1056:1: note: 
      '_mm_cvtsi128_si64' declared here
_mm_cvtsi128_si64(__m128i __a)
^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:9:
./Math/gf2n.h:69:37: error: invalid use of member 'a' in static member function
  static int size() { return sizeof(a); }
                                    ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:10:
In file included from ./Math/modp.h:23:
./Math/Zp_Data.h:106:7: error: expected '(' after 'asm'
  asm goto ("jc %l[sub]" :::: sub);
      ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:10:
./Math/modp.h:62:15: error: friend declaration specifying a default argument
      must be the only declaration
  friend void to_bigint(bigint& ans,const modp& x,const Zp_Data& ZpD,boo...
              ^
./Math/Zp_Data.h:71:16: note: previous declaration is here
   friend void to_bigint(bigint& ans,const modp& x,const Zp_Data& ZpD,bo...
               ^
2 warnings and 5 errors generated.
make: *** [Math/Setup.o] Error 1

**Comment by mkskeller** [comment]
SPDZ only compiles with GCC as in GNU Compiler Collection. g++ on OS X is an alias of clang. You can verify this by calling `g++ -version`.
