### ISSUE TITLE
MAC faulire with tutorial

### ISSUE THREAD

**Issue by ghost** [bristolcrypto/SPDZ-2#21]
While checking latest master (both SPDZ and MPIR) tutorial I got following error:
env LD_LIBRARY_PATH=./ ./Server.x 2 5000
Bound on port 4999
Waiting for player 0
Connected to player 0
Waiting for player 1
Connected to player 1
Player 0 started.
Player 0 is on machine xbell
Player 1 started.
Player 1 is on machine xbell
______________________
Waiting for thread 0 to be ready
        I am in thread 0
Using single-threaded receiving
Setting up client to xbell:5001 with id 0x3
Setting up server with id 0x2
Setting up server with id 0x3
        Set up player in thread 0
Setting up Data_Files in: Player-Data/2-128-40/
done
Using indirect communication.
Opening file Programs/Public-Input/tutorial
Opening file Player-Data/Private-Input-1
Opening file Player-Data/Public-Output-1
Opening file Player-Data/Private-Output-1
Locking for sync of thread 0
terminate called after throwing an instance of 'mac_fail'
  what():  MacCheck Failure
 “env LD_LIBRARY_PATH=./ ./Player…” terminated by signal SIGABRT (Abort)
___________________________________
Locking for sync of thread 0
expected 3, got 3
expected 2, got 2
expected 2, got 2
expected 1, got 1
expected -1, got -1
expected 1, got 1
expected 1, got 1
expected 0, got 0
expected 0, got 0
expected 0, got 0
expected 1, got 1
expected 3, got 0x3
expected 0, got 0x0
expected 2, got 0x2
expected 1, got 0x1
expected 0, got 0x0
expected 1, got 0x1
expected 9801, got 9801
expected 789, got 789
terminate called after throwing an instance of 'mac_fail'
  what():  MacCheck Failure
 “env LD_LIBRARY_PATH=./ ./Player…” terminated by signal SIGABRT (Abort)
_____________________________

Any ideas what I'm doing wrong?

**Comment by rdragos** [comment]
Try to make a clean installation again by first running 'make clean' and remove any files inside the Player-Data/ folder. 

Next step is to run 'make' command and then the Setup-Online.sh script.
