### ISSUE TITLE
ot-offline.x runs forever when generating bits in Zp

### ISSUE THREAD

**Issue by lkowalcz** [bristolcrypto/SPDZ-2#22]
When I run the offline phase code with both the -P and -B options (requesting Zp as the field and asking it to generate bits), it seems to run forever.

Has anyone else encountered this / have a workaround?

Specifically, running:
`./ot-offline.x -n 1000 -N 2 -B -P -p 0 -o` 
`./ot-offline.x -n 1000 -N 2 -B -P -p 1 -o`

runs forever, but removing either -B or -P works.

Thanks!

**Comment by mkskeller** [comment]
This should be fixed now. Thank you for alerting this.
