### ISSUE TITLE
Difficulty compiling SPDZ-2

### ISSUE THREAD

**Issue by Pralhad-Deshpande** [bristolcrypto/SPDZ-2#23]
I've made sure that GCC is the compiler. But still I am unable to compile SPDZ-2. 

Pralhads-MacBook-Pro:SPDZ-2 pralhad$ g++ --version
g++-6 (Homebrew GCC 6.4.0) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Pralhads-MacBook-Pro:SPDZ-2 pralhad$ gcc --version
gcc-6 (Homebrew GCC 6.4.0) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

-----------------

Pralhads-MacBook-Pro:SPDZ-2 pralhad$ make
g++   -g -Wextra -Wall -O3 -I. -pthread      '-DPREP_DIR="Player-Data/"' -maes -mpclmul -msse4.1 -mtune=native  -c -o Math/Setup.o Math/Setup.cpp
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:9:
In file included from ./Math/gf2n.h:12:
In file included from ./Tools/random.h:8:
./Tools/aes.h:53:16: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
__attribute__((optimize("unroll-loops")))
               ^
./Tools/aes.h:65:16: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
__attribute__((optimize("unroll-loops")))
               ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:9:
In file included from ./Math/gf2n.h:14:
./Math/gf2nlong.h:109:37: error: invalid use of member 'a' in static member function
  static int size() { return sizeof(a); }
                                    ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:9:
./Math/gf2n.h:69:37: error: invalid use of member 'a' in static member function
  static int size() { return sizeof(a); }
                                    ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:10:
In file included from ./Math/modp.h:23:
./Math/Zp_Data.h:106:7: error: expected '(' after 'asm'
  asm goto ("jc %l[sub]" :::: sub);
      ^
In file included from Math/Setup.cpp:5:
In file included from ./Math/gfp.h:10:
./Math/modp.h:62:15: error: friend declaration specifying a default argument must be the
      only declaration
  friend void to_bigint(bigint& ans,const modp& x,const Zp_Data& ZpD,bool reduce=true);
              ^
./Math/Zp_Data.h:71:16: note: previous declaration is here
   friend void to_bigint(bigint& ans,const modp& x,const Zp_Data& ZpD,bool reduce);
               ^
2 warnings and 4 errors generated.
make: *** [Math/Setup.o] Error 1

**Comment by Pralhad-Deshpande** [comment]
I was able to install mpir-3.0.0

**Comment by mkskeller** [comment]
The errors are exactly the ones that show up when compiling with clang. Can you hardcode the path of GCC into `Makefile`, that is, set `CXX` to the output of `which g++`?

**Comment by Pralhad-Deshpande** [comment]
Pralhads-MacBook-Pro:SPDZ-2 pralhad$ which g++
/usr/bin/g++

---------------
I edited the Makefile so the first few lines read like this:

include CONFIG
CXX = /usr/bin/g++
MATH = $(patsubst %.cpp,%.o,$(wildcard Math/*.cpp))

---------------

make still gives errors. Not the same ones as before but they look similar. 

Pralhads-MacBook-Pro:SPDZ-2 pralhad$ make
/usr/bin/g++  -g -Wextra -Wall -O3 -I. -pthread      '-DPREP_DIR="Player-Data/"' -maes -mpclmul -msse4.1 -mtune=native Scripts/gen_input_f2n.cpp	-o gen_input_f2n.x Math/Integer.o Math/Setup.o Math/Share.o Math/Zp_Data.o Math/bigint.o Math/gf2n.o Math/gf2nlong.o Math/gfp.o Math/modp.o Tools/Commit.o Tools/Lock.o Tools/MMO.o Tools/Signal.o Tools/aes-ni.o Tools/aes.o Tools/mkpath.o Tools/octetStream.o Tools/random.o Tools/sha1.o Tools/time-func.o Networking/Player.o Networking/Receiver.o Networking/Sender.o Networking/ServerSocket.o Networking/sockets.o Auth/MAC_Check.o Auth/Subroutines.o Auth/Summer.o Auth/fake-stuff.o -lmpirxx -lmpir  -lm -lpthread
In file included from Scripts/gen_input_f2n.cpp:5:
In file included from ./Math/gf2n.h:12:
In file included from ./Tools/random.h:8:
./Tools/aes.h:53:16: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
__attribute__((optimize("unroll-loops")))
               ^
./Tools/aes.h:65:16: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
__attribute__((optimize("unroll-loops")))
               ^
In file included from Scripts/gen_input_f2n.cpp:5:
In file included from ./Math/gf2n.h:14:
./Math/gf2nlong.h:109:37: error: invalid use of member 'a' in static member function
  static int size() { return sizeof(a); }
                                    ^
In file included from Scripts/gen_input_f2n.cpp:5:
./Math/gf2n.h:69:37: error: invalid use of member 'a' in static member function
  static int size() { return sizeof(a); }
                                    ^
2 warnings and 2 errors generated.
make: *** [gen_input_f2n.x] Error 1

**Comment by TomMD** [comment]
Could you post versions such as `g++ --version`?

**Comment by Pralhad-Deshpande** [comment]
Pralhads-MacBook-Pro:SPDZ-2 pralhad$ g++ --version
g++-6 (Homebrew GCC 6.4.0) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Pralhads-MacBook-Pro:SPDZ-2 pralhad$ gcc --version
gcc-6 (Homebrew GCC 6.4.0) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mkskeller** [comment]
Just to be sure, can you run `/usr/bin/g++ --version`?

**Comment by Pralhad-Deshpande** [comment]
Pralhads-MacBook-Pro:SPDZ-2 pralhad$ /usr/bin/g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by mkskeller** [comment]
So /usr/bin/g++ is not GCC. You'll have to find out the location of the GCC g++.

**Comment by Pralhad-Deshpande** [comment]
Pralhads-MacBook-Pro:SPDZ-2 pralhad$ /usr/local/Cellar/gcc@6/6.4.0/bin/g++-6 --version
g++-6 (Homebrew GCC 6.4.0) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mkskeller** [comment]
So there you go.

**Comment by Pralhad-Deshpande** [comment]
I edited CONFIG as below: 
CXX = /usr/local/Cellar/gcc@6/6.4.0/bin/g++-6
LD = /usr/local/Cellar/gcc@6/6.4.0/bin/g++-6

------------ 

Now I am getting a different type of error: 

Pralhads-MacBook-Pro:SPDZ-2 pralhad$ make
/usr/local/Cellar/gcc@6/6.4.0/bin/g++-6   -g -Wextra -Wall -O3 -I. -pthread      '-DPREP_DIR="Player-Data/"' -maes -mpclmul -msse4.1 -mtune=native Scripts/gen_input_f2n.cpp	-o gen_input_f2n.x Math/Integer.o Math/Setup.o Math/Share.o Math/Zp_Data.o Math/bigint.o Math/gf2n.o Math/gf2nlong.o Math/gfp.o Math/modp.o Tools/Commit.o Tools/Lock.o Tools/MMO.o Tools/Signal.o Tools/aes-ni.o Tools/aes.o Tools/mkpath.o Tools/octetStream.o Tools/random.o Tools/sha1.o Tools/time-func.o Networking/Player.o Networking/Receiver.o Networking/Sender.o Networking/ServerSocket.o Networking/sockets.o Auth/MAC_Check.o Auth/Subroutines.o Auth/Summer.o Auth/fake-stuff.o -lmpirxx -lmpir  -lm -lpthread
Undefined symbols for architecture x86_64:
  "Player::Broadcast_Receive(std::vector<octetStream, std::allocator<octetStream> >&, bool) const", referenced from:
      Open_Challenge(std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<octetStream, std::allocator<octetStream> >&, std::vector<octetStream, std::allocator<octetStream> > const&, Player const&, int) in Subroutines.o
      Open(std::vector<std::vector<octetStream, std::allocator<octetStream> >, std::allocator<std::vector<octetStream, std::allocator<octetStream> > > >&, std::vector<std::vector<octetStream, std::allocator<octetStream> >, std::allocator<std::vector<octetStream, std::allocator<octetStream> > > > const&, std::vector<octetStream, std::allocator<octetStream> > const&, Player const&, int, int) in Subroutines.o
      Open(std::vector<std::vector<octetStream, std::allocator<octetStream> >, std::allocator<std::vector<octetStream, std::allocator<octetStream> > > >&, std::vector<std::vector<octetStream, std::allocator<octetStream> >, std::allocator<std::vector<octetStream, std::allocator<octetStream> > > > const&, std::vector<octetStream, std::allocator<octetStream> > const&, std::vector<int, std::allocator<int> >, Player const&, int) in Subroutines.o
      Create_Random_Seed(unsigned char*, Player const&, int) in Subroutines.o
      void Commit_And_Open<gf2n_short>(std::vector<gf2n_short, std::allocator<gf2n_short> >&, Player const&) in Subroutines.o
      void Commit_And_Open<gfp>(std::vector<gfp, std::allocator<gfp> >&, Player const&) in Subroutines.o
      void Create_Random<gf2n_short>(gf2n_short&, Player const&) in Subroutines.o
      ...
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__append(unsigned long) in Player.o
      __ZNSt3__16vectorINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS4_IS6_EEE6assignIPS6_EENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr16is_constructibleIS6_NS_15iterator_traitsISC_E9referenceEEE5valueEvE4typeESC_SC_ in Player.o
      void std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__push_back_slow_path<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Player.o
      std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in Player.o
      std::__1::vector<octetStream, std::__1::allocator<octetStream> >::vector(unsigned long) in Player.o
      void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int const>(int const&) in Player.o
      void std::__1::vector<Receiver*, std::__1::allocator<Receiver*> >::__push_back_slow_path<Receiver* const>(Receiver* const&) in Player.o
      ...

**Comment by mkskeller** [comment]
You do `make clean` when you change compiler.

**Comment by Pralhad-Deshpande** [comment]
Aha! Thank you! Compiled!
