### ISSUE TITLE
GF2N Field Size

### ISSUE THREAD

**Issue by danesmith** [bristolcrypto/SPDZ-2#25]
Currently, only 4, 8, 28, and 40 bit fields are supported for GF2N. Are there any plans to extend this beyond 40?

Additionally, the command line arguments for gf2n do not specify the currently valid sizes. For example: Fake-Offline has ```-lg2, --lg2 ARG                 Bit length of GF(2^n) field (default: 40)``` If the only supported sizes are going to be the ones noted above, they should be listed as choices.

**Comment by rdragos** [comment]
You can use the online phase with a GF2N of 128 bits. To do this you need to set the USE_GF2N_LONG=1 flag in the CONFIG file, compile again and then tune the parameters of setup-online.sh accordingly.
