### ISSUE TITLE
Protocol requirements

### ISSUE THREAD

**Issue by marinedejoux** [bristolcrypto/SPDZ-2#27]
Hi everyone,

I am trying to compile SPDZ2 protocol. I have done all the requirements as indicated in the instructions. When I compile with the make command, I still have some errors.

The first error is 
"Makefile:95: recipe for target 'spdz2-offline.x' failed
make: *** [spdz2-offline.x] Error 1"
I have checked that I have the file spdz2-offline.cpp but during the compilation, it seems to be that this file is not transformed into spdz2-offline.x.

The other error is
![error2](https://user-images.githubusercontent.com/18051919/33891378-1171302e-df56-11e7-9228-efbfb1f54ab0.jpg)

If anyone has a clue to solve those issues, it would be awesome. Thanks
Marine

**Comment by mkskeller** [comment]
Can you make sure that make calls g++ instead of gcc? SPDZ is written in C++, and we've written Makefile such that g++ would be called by default.

**Comment by marinedejoux** [comment]
I tried and it worked thanks very much.
