### ISSUE TITLE
How to provide input to SPDZ?

### ISSUE THREAD

**Issue by lilir5** [bristolcrypto/SPDZ-2#3]
Hi everybody 

I want to run the addition and multiplication operation in SPDZ. I followed all the steps according to the "read me" file and Tutorial , just not sure about the last step on how to provide inputs for SPDZ because the addition result doesn’t seem correct. I have two integers and want to convert them to binary , I used gen_input_fp.cpp on integer number as following: 

1- made gfp-vals.in and wrote an integer number in it 
2- run gen_input_fp.cpp 
3-  Copy the out put file to Player-Data
/Private-Input-{i}
( I use following commands for making addition : a = sint.get_raw_input_from(0)
b = sint.get_raw_input_from(1)
c = a + b
print_ln('Result is %s', c.reveal()) )

Have I missed anything? Should I receive the clear result ?
Any hint is highly appreciated.

**Comment by volsusdev** [comment]
What is your input for gfp-vals.in? I used e.g. the following as input an get a working binary file:

`
1
10
`

As described [here](https://groups.google.com/forum/#!topic/spdz/gv039B2oGy8) the first value is supposed to be the number of other inputs follows in this file.

**Comment by lilir5** [comment]
Hi 
Thank you for the link. It is working now. Does SPDZ support multi array inputs?

**Comment by mkskeller** [comment]
What do you mean by multi array inputs? You can always specify several inputs and fill an array or multi array by looping.
