### ISSUE TITLE
Testing SPDZ with 3 players

### ISSUE THREAD

**Issue by marinedejoux** [bristolcrypto/SPDZ-2#32]
Hello everyone, 

I managed to follow your tutorial and implement the Computation on Secret Shared data. 

Now I would like to do the same with 3 players. However, I can't get it to work. Has anyone managed to test this program with 3 players ?

Here is what I did:
In /Programs/Source, I have the following python code:
_# coding=utf-8

a = sint.get_raw_input_from(0)
b = sint.get_raw_input_from(1)
c = sint.get_raw_input_from(2)

seuil = cint(500)

result = a + b +c
if (result <= seuil ) :
    print_ln('Result is %s Vous êtes en dessous du seuil', result.reveal())
else :
    print_ln('Result is %s Vous avez dépassé le seuil.', result.reveal())_

In ./Scripts/setup-Online.sh, in order to have 3 players, I have changed the value players=${1:-2} into  players=${2:-3}

When I run the command sh Scripts/setup-online.sh 3 128 40, I have the following error

_terminate called after throwing an instance of 'file_error'
  what():  File Error : Player-Data/128-128-40/Inputs-p-P6-7
Aborted (core dumped)
1+0 enregistrements lus
1+0 enregistrements écrits
10000 bytes (10 kB, 9,8 KiB) copied, 0,00433587 s, 2,3 MB/s
1+0 enregistrements lus
1+0 enregistrements écrits
10000 bytes (10 kB, 9,8 KiB) copied, 0,000128974 s, 77,5 MB/s_

Thanks for your help,

Marine

**Comment by mkskeller** [comment]
There is no need to change the script. The defaults are overwritten the arguments. If you would like to set the default to 3, the line would be `players=${1:-3}`.

**Comment by marinedejoux** [comment]
Thank you very much for your prompt answer, I will try with this solution.
