### ISSUE TITLE
Error using sint.get_raw_input_from for 3 players

### ISSUE THREAD

**Issue by marinedejoux** [bristolcrypto/SPDZ-2#34]
Hello everyone,

I managed to use the script with two players from the tutorial which uses sint.get_raw_input_from in order to get data from the players. When I try with three players, the following program does not work: 
_# coding=utf-8
a = sint.get_raw_input_from(0)
b = sint.get_raw_input_from(1)
c= sint.get_raw_input_from(2)
seuil = sint(500)
result = a + b + c
if (result <= seuil ) :
    print_ln('Result is %s Vous êtes en dessous du seuil', result.reveal())
else :
    print_ln('Result is %s Vous avez dépassé le seuil.', result.reveal())_

I get the following error. 
_terminate called after throwing an instance of 'file_error'
  what():  File Error : IO problem when buffering gfp from private input_

Does anyone has an idea of what the problem could be ?

Thank you so much for your help. 

Marine

**Comment by mkskeller** [comment]
There is a section "Providing input to SPDZ" in `tutorial.md` regarding `get_raw_input_from()`. Essentially, you need to run `gen_input_fp.x` first.

**Comment by marinedejoux** [comment]
Hello, 
Thank you so much for your prompt answer. I tried to adapt the script with your suggestion. 

I have the following Script to execute the program for 3 players:
_#!/bin/bash

make clean

echo $LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH
echo $LD_LIBRARY_PATH

./compile.py -p 128 addition3Test

sh Scripts/setup-online.sh 3

echo 'ok1'
./gen_input_fp.x 
echo 'ok2'
./gen_input_f2n.x
echo 'ok3'

./Server.x 3 5000 > toto.txt 2>&1 &
gnome-terminal -e  "./Player-Online.x -pn 5000 0 addition3Test"
gnome-terminal -e  "./Player-Online.x -pn 5000 1 addition3Test"
gnome-terminal -e  "./Player-Online.x -pn 5000 2 addition3Test"_

The file addition3Test.mpc is 
_# coding=utf-8

a = sint.get_raw_input_from(0)
b = sint.get_raw_input_from(1)
c = sint.get_raw_input_from(2)

d = a + b + c

print_ln('Result is %s', d.reveal())_


However, I still get two errors. The first one is (from server):
_Using indirect communication.
Opening file Programs/Public-Input/addition3Test
Opening file Player-Data/Private-Input-2
Opening file Player-Data/Public-Output-2
Opening file Player-Data/Private-Output-2
Locking for sync of thread 0
terminate called after throwing an instance of 'file_error'
  what():  File Error : IO problem when buffering gfp from private input_

The second one is (from players): 
_ Receiving error - 1: Connection reset by peer
terminate called after throwing an instance of 'bad_value'
  what():  Some value is wrong somewhere_

Do not hesitate to tell me if you need further information,

Thank you in advance for your help,

Best regards,

Marine

**Comment by mkskeller** [comment]
You have to move the output of the gen_input_f*.x programs to Player-Data/Private-Input-<playerno>. It seems that Player-Data/Private-Input-2 is missing. I have pushed a commit that should name the missing file in the error message.

**Comment by marinedejoux** [comment]
Hello, 

Thanks for your great advices. It works now !!!

Marine
