### ISSUE TITLE
Missing .x Files

### ISSUE THREAD

**Issue by edoroth** [bristolcrypto/SPDZ-2#43]
When I compile any of the source files, compilation seems to go smoothly, with the correct bytecode and schedule files. I'm not sure how to actually run any of the programs, though. How are the .x files (Server.x,  Player-Online.x) generated?

**Comment by mkskeller** [comment]
There is another process of compilation for this, called by `make`. However, note that you have to install some requirements, most notably MPIR. For that you have to familiarize with the "configure, make, make install" paradigm.

**Comment by edoroth** [comment]
I have installed MPIR, and run through these steps. Any idea why it may not be getting generated?

**Comment by edoroth** [comment]
I actually figured out the issue with linking of MPIR. Sorry about that!
