### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by edoroth** [bristolcrypto/SPDZ-2#44]
I'm able to compile and was able to run a few test cases. However, when I tried again, somehow it wasn't able to locate the shared library. Do you have any idea why this is the case? I make sure I link to the proper folder and 'make' works properly. Just get this strange error when running. Would appreciate any help!

./Server.x: error while loading shared libraries: libmpirxx.so.8: cannot open shared object file: No such file or directory

**Comment by mkskeller** [comment]
You have to make sure that you have configured MPIR with C++ support (hence libmpirxx.so.8 was compiled), and that LD_LIBRARY_PATH includes the directory where you have it installed.
