### ISSUE TITLE
Error while compiling SPDZ-2

### ISSUE THREAD

**Issue by cli0** [bristolcrypto/SPDZ-2#46]
Hi, 

when I first cloned your repo, the content of SimpleOT did not load as well (since it was an external repo) and when I tried to compile SPDZ-2, I would get an error pertaining to missing files in SimpleOT. So I cloned and stored the content of that repo inside SPDZ's SimpleOT folder. However, I still get this error message when I run `make`

```
g++: error: SimpleOT/libsimpleot.a: No such file or directory
Makefile:74: recipe for target 'ot.x' failed
make: *** [ot.x] Error 1
```
Something is wrong with SimpleOT again due to missing files in the original SimpleOT repo. Can someone help me figure out how to solve the missing file issue?

**Comment by mkskeller** [comment]
You need to checkout SimpleOT and then compile it:
```
git submodule update SimpleOT
cd SimpleOT
make -j
```

**Comment by cli0** [comment]
Yes, you were right. I had not compiled it and now it works.
