### ISSUE TITLE
Path error in almost all the files

### ISSUE THREAD

**Issue by crisajith** [bristolcrypto/SPDZ-2#48]
I am getting path error while compiling this library. Pointing out one issue. In the file https://github.com/bristolcrypto/SPDZ-2/blob/master/OT/BitMatrix.h , there are include statements like 

#include "Tools/random.h"
#include "Tools/MMO.h"
#include "Math/gf2nlong.h"

Since the above mentioned folders (Tools, Math) are located outside "OT" folder, a "File not found" error is thrown. Should it be of the form

#include "../Tools/random.h"
#include "../Tools/MMO.h"
#include "../Math/gf2nlong.h"
??
If this is a valid issue, the same issue is there with lot of files.
Hoping a fix (or reply) soon.

**Comment by mkskeller** [comment]
We include `-I$(ROOT)` in `CFLAGS`, where `ROOT` is set to the current directory. If you compile not from the root directory, you can change this in `CONFIG`.
