### ISSUE TITLE
Compiling SimpleOT not working in 64-bit mode

### ISSUE THREAD

**Issue by fgadaleta** [bristolcrypto/SPDZ-2#50]
After pulling SimpleOT, compilation terminates with 

```
fe25519_freeze.s:213:1: error: 32-bit absolute addressing is not supported in 64-bit mode
movq CONST_REDMASK51,%rax
```

**Comment by mkskeller** [comment]
SimpleOT has a separate repository: https://github.com/pascholl/SimpleOT
Have you tried their latest commit?

**Comment by fgadaleta** [comment]
It is indeed about SimpleOT. I raised an issue there too. My question is, how do you guys compile then? As you also rely on SimpleOT library. Are you in 32-bit mode?

**Comment by mkskeller** [comment]
No, I'm using 64-bit mode. I've had some problems with newer version of Linux, but they got fixed in the latest commit of SimpleOT, and I just now updated SPDZ-2 to use that.

**Comment by fgadaleta** [comment]
Is pulling SimpleOT separately from SPDZ-2 the way to go?

<https://about.me/fgadaleta?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Francesco Gadaleta
about.me/fgadaleta
<https://about.me/fgadaleta?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by mkskeller** [comment]
If you now pull the latest SPDZ-2, you should get it automatically. Otherwise yes. Just make sure SimpleOT is on cbe71d3eac29836ac58711474f985f2db7e5af41.

**Comment by fgadaleta** [comment]
Installed all on Linux VM and seems to work.
One more reason to get rid of Mac OS :/

Thanks

<https://about.me/fgadaleta?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Francesco Gadaleta
about.me/fgadaleta
<https://about.me/fgadaleta?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
