### ISSUE TITLE
Can I read data from files other than player's private input data?

### ISSUE THREAD

**Issue by maoth** [bristolcrypto/SPDZ-2#52]
I am writing a program using SPDZ-2 and this program requires to read lots of data from a text file. So I am wondering that how to read data from an external file? Is there only one way to read data that from private input of players?
There is another problem in this question, how to read a secret shared float data(or a fix point data) in a player's private input? Which means how to read a data with the type of sfix or sfloat from private input.
I tried sfix.get_raw_input_from and sfloat.get_raw_input_from and get the compile error.
I am very grateful for your help.

**Comment by mkskeller** [comment]
There is public_input() if you would to read public input data, and there's sint.get_input_from() that reads input from the stdin, but it is slower than sint.get_raw_input_from().
There is not input functionality for sfix and sfloat.

**Comment by maoth** [comment]
Is that means the only method to give the data to a variable is using an assignment statement like a=sfix(1.0)? So that if I want to use an array with double type data in the program I need to give each of element in the array in my mpc script?
I found a discussion in the google group mentioned that a real number could be described by four integers so that the program could read integers from private data of players, is this could be supported in SPDZ-2? If this works, how to use integers to describe the real number in the private data? Thanks.

**Comment by rdragos** [comment]
You can scale your numbers by 2^f (where f is typically 20) and then round them as integers. Then you can initialize the sfix from the sints...

This way you avoid parsing real values from the Private-Input data and parse numbers as integers.

To sum up:
- take your real value numbers, convert them to integers by multiplying them with 2^f 
- use gen_input_fp.x to convert them to SPDZ values
- load each sint to sfix

**Comment by mkskeller** [comment]
There is a difference between fixed-point and floating-point numbers: The former are represented internally by one sint, and can be used as described by Dragos. It's floating-point numbers that are represented by four values (significand, exponent, sign, zero).

**Comment by maoth** [comment]
I tried the methods before and I an writing my program now, thanks for your help again.
There is a last question of this topic, how to change the type cint/sint to int?(because I want to read an integer as the times of a loop)

**Comment by rdragos** [comment]
I guess you can do the loops using the @for_range structure.

Problem is that the compiler will fail to parallelize operations in the loop since the bound on the for is a run-time integer. In that sense the compiler is limited: it cannot merge communication rounds dynamically with run-time arguments (such as cint, regint, etc)
