### ISSUE TITLE
'valgrind/callgrind.h' file not found

### ISSUE THREAD

**Issue by callzhang** [bristolcrypto/SPDZ-2#57]
When `make`, I had this error. Installing valgrind on my MacOS doesn't solve this issue.
```
pairwise-offline.cpp:4:10: fatal error: 'valgrind/callgrind.h' file not found
#include <valgrind/callgrind.h>
...
simple-offline.cpp:9:10: fatal error: 'valgrind/callgrind.h' file not found
#include <valgrind/callgrind.h>
...
```

**Comment by mkskeller** [comment]
You might need to point the compiler to the location of valgrind. For example, if `callgrind.h` is at `/foo/bar/valgrind/callgrind.h`, you need to add `-I/foo/bar` to `CFLAGS`.

**Comment by callzhang** [comment]
@mkskeller Thanks for your reply. I have cloned the valgrind repo from [here](http://valgrind.org/downloads/repository.html). However, the folder structure is different. The `callgrind.h` is located at _./callgrind/callgrind.h_ 
Is it due to version difference? If so, what version are you specifically using here?

**Comment by mkskeller** [comment]
I'm using version 3.13. However, I suspect that cloning might not be enought, you would also need to install to allow linking.

**Comment by callzhang** [comment]
I changed the ‘configure’ to default and compiled it. Then it worked fine. Lesson learned: do not use the compiling instruction described on the website :)
