### ISSUE TITLE
Readme link to University of Bristol Cryptography resource broken

### ISSUE THREAD

**Issue by das-sein** [bristolcrypto/SPDZ-2#58]
Hello,

Just reporting that the link on the README is broken.

This one specifically: https://www.cs.bris.ac.uk/Research/CryptographySecurity/SPDZ

I was only able to find the SCALE-MAMBA page here: https://homes.esat.kuleuven.be/~nsmart/SCALE/

**Comment by mkskeller** [comment]
Removed.

**Comment by das-sein** [comment]
> Removed.

Is there an updated link to the resources or are the resources considered dead as well?

**Comment by mkskeller** [comment]
As I've said in the readme, the SCALE page is a copy of the old page in most respects. I'm not with Bristol Uni anymore, so I don't have any influence over what is hosted there. Neither do I have a copy of the contents as it was maintained by Nigel.

**Comment by das-sein** [comment]
Ah, sorry for missing that. Thank you.
