### ISSUE TITLE
Invalid commitment error

### ISSUE THREAD

**Issue by wzheng** [bristolcrypto/SPDZ-2#60]
Hello! I'm trying to benchmark the MASCOT offline phase for bit generation and with 3 parties, but am getting "terminate called after throwing an instance of 'invalid_commitment' what():  Invalid Commitment" as an error. 

In general, the MASCOT and the Overdrive offline phases do not seem to support bit generation for more than 2 parties. Is this the case? Thanks!

**Comment by mkskeller** [comment]
I have fixed some bugs; it should work now both with MASCOT and High Gear.

**Comment by wzheng** [comment]
Just ran the benchmarks and they work very well! Thank you so much!
