### ISSUE TITLE
Core dumped error while running SPDZ

### ISSUE THREAD

**Issue by fairaschain** [bristolcrypto/SPDZ-2#62]
Hi, I am new to SPDZ implementation. I am running aes.mpc for 3 players and I am getting core dumped error while executing it.

First I initialized offline parameters for all 3 players as follows:
printf "64\n0x87 0x2D 0x1A 0x05 0xE1 0xBE 0x2D 0x2B 0x0A 0xC3 0x80 0x92 0x59 0xB2 0xBB 0x37 0x96 0x18 0x5F 0x03 0x73 0x24 0xCB 0x82 0xF4 0xC5 0xF9 0xF0 0xB9 0x67 0xDD 0x87 0x8A 0x2A 0x81 0x3D 0xB1 0x17 0xD9 0xF4 0xF7 0x36 0xDA 0xBC 0x4B 0x50 0x63 0x8B 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" > gf2n_vals.in
./gen_input_f2n.x
cat gf2n_vals.out > Player-Data/Private-Input-0

Similarly, for all 3 players. 

Then, I compiled .mpc file.

Then I executed my Server.x and Player-Online.x for all 3 players and I got following output:

ServerSocket is bound on port 4999
Waiting for player 0
Connected to player 0
Waiting for player 1
Connected to player 1
Waiting for player 2
Connected to player 2
Player 0 started.
Player 0 sent (IP for info only) 127.0.0.1:5000
Client IP address: 127.0.0.1
Player 1 started.
Player 1 sent (IP for info only) 127.0.0.1:5001
Client IP address: 127.0.0.1
Player 2 started.
Player 2 sent (IP for info only) 127.0.0.1:5002
Client IP address: 127.0.0.1
./run_aes3.sh: line 6:  6176 Aborted                 (core dumped) ./Player-Online.x -pn 5000 1 aes_test_3player &> /dev/null
./run_aes3.sh: line 6:  6178 Aborted                 (core dumped) ./Player-Online.x -pn 5000 2 aes_test_3player &> /dev/null
ServerSocket is bound on port 4999
Waiting for player 0
./run_aes3.sh: line 6:  6174 Aborted                 (core dumped) ./Player-Online.x -pn 5000 0 aes_test_3player &> /tmp/output$i

I have set

MOD = -DMAX_MOD_SZ=6
USE_GF2N_LONG = 1

in the config file. I don't understand what is the issue. Any help will be appreciated.

**Comment by mkskeller** [comment]
Can you run without redirecting to /dev/null? Or even better, using valgrind?
