### ISSUE TITLE
Recursion Maximum Depth Exceeded

### ISSUE THREAD

**Issue by ryandeng1** [bristolcrypto/SPDZ-2#64]
When I am running ./compile.py on a program, I triggered a recursion maximum depth exceeded error in Line 111 of Compiler/Allocator.py.

Any reason why this might be happening?

My .mpc file is essentially doing many matrix multiplications and this happens when the dimensions of the matrices get over 25. 

On the compiler output, the error occurs after it says "Processing tape for [Program Name]"

Thanks

**Comment by mkskeller** [comment]
The line is related to scopes that are created e.g. by loops. It might that your program involves an unusually high number of loops. In particular, a runtime loop (using decorators like `@for_range`) inside a plain Python loop (`for`) can create a program too large for the compiler. If that is the case, use runtime loops for all outer loops. However, it is hard to comment without known the actual program.

**Comment by ryandeng1** [comment]
I think I fixed the issue. I was calling reveal() many times in my program and forgot to remove those statements after finishing debugging. Thanks for the help!
