### ISSUE TITLE
cint to int

### ISSUE THREAD

**Issue by jimouris** [bristolcrypto/SPDZ-2#66]
Hello,

I am working with @cnasikas and we have a problem with cint data type when using it as a first argument in `receive_from_client`. For instance:
```
x = sint(5)
x_clear = x.reveal()
print_ln('x is %s', x_clear)

y_clear = x_clear + 2
print_ln('y_clear is %s', y_clear)

client_inputs = sint.receive_from_client(y_clear, client_socket_id)
```
The error that occurs is the following:
```
... line 42, in accept_client_input
    client_inputs = sint.receive_from_client(y_clear, client_socket_id)
  File ".../SPDZ-2/Compiler/types.py", line 991, in receive_from_client
    triples = list(itertools.chain(*(sint.get_random_triple() for i in range(n))))
TypeError: range() integer end argument expected, got cint.
```

The problem here is that the first argument of `receive_from_client` is used in the `range()` method. Is there any way to get the clear int value from cint?

Thanks in advance,
Dimitris

**Comment by mkskeller** [comment]
There is no such conversion because the value of a cint is only known at runtime whereas an int has to be known at compile time. You might use the `for_range(n)` construct instead.

**Comment by jimouris** [comment]
Can I use inside the `for_range(n)` other variable types except `cint` or `sint` arrays? For example, in the `tutorial.mpc`, an array of sints (`a`) is passed in the loop.
```
a = Array(100, sint)
@for_range(100)
def f(i):
    a[i] = sint(i)**2
```
Another example is in the `bankers_bonus.mpc` program where in the `determine_winner` method it is passed an array of one position instead of a single variable:
```
max_value = Array(1, sint)
max_value[0] = client_values[0]
...
@for_range(number_clients-1)
def loop_body(i):
    is_new_max = max_value[0] < client_values[i+1]
    max_value[0] = if_else(is_new_max, client_values[i+1], max_value[0])
    ...
```
So, my actual question is if there is an array of ints that I can pass to `for_range`.

**Comment by mkskeller** [comment]
Arrays are the preferred way of passing data out of the loop. What other variable types are you thinking of?

**Comment by jimouris** [comment]
An array of ints, not cints or sints.

**Comment by mkskeller** [comment]
It depends on how you want to use them. You cannot address a Python array (which lives in compile-time space) by a run-time number such as cint or regint.

**Comment by mkskeller** [comment]
Note that you can assign an integer array to an Array:
```
a = Array(3, cint)
a.assign([9, 8, 7])
@for_range(3)
def _(i):
    print_ln('%s', a[i])
```

**Comment by jimouris** [comment]
Thanks, but that does not help. Let me clarify the problem that I am facing.

I want to pass an array from a client (ExternalIO cpp file) to the players (.mpc file) and finally manipulate it and print it.

The way I am trying to do it is to use `receive_from_client` two times; the first time to pass the size of the array and the second to use this size in order to receive the correct number of sints. Below is the code from the .mpc file that produces the errror:

```
first_packet = sint.receive_from_client(2, client_socket_id)
array_size = first_packet[1].reveal()

new_size = array_size + 2
print_ln('New size %s \n', new_size) # Correct number is printed here (but it is a cint type)
client_inputs = sint.receive_from_client(new_size, client_socket_id) # Here the error occurs due to the new_size variable
```

Thank you for your help.

**Comment by mkskeller** [comment]
Have you tried the following?
```
upper_bound = 1000

client_inputs = Array(upper_bound, sint)
@for_range(new_size)
def _(i):
    sint.receive_from_client(1, client_socket_id)
```

**Comment by jimouris** [comment]
It does compile that way, thanks. I hadn't thought of using an **upper bound**. However, using this I get a different error:

```
Incorrect triple at 1, aborting
```

After the first two sints are sent through the `first_packet` (`my_client_id` and `array_size`), this error occurs on the `sint.receive_from_client(1, client_socket_id)` inside the `for_range` loop. I printed the triplets and the third one is zero.

The gfp-vector that I am sending with the second `send_private_inputs` has size `array_size + 2`. The first position is the `my_client_id`, the next `array_size` are the values of the array, and the last one is the `finish` bit.

Any ideas on this?

**Comment by mkskeller** [comment]
Have you tried running another program such as the tutorial on the same setup? It could be that it's just the setup that is broken.

**Comment by jimouris** [comment]
Yes, I tried that, other programs work fine.

**Comment by mkskeller** [comment]
As this error message comes from the client code in ExternalIO, I would need to see your modifications in order to further comment on it.

**Comment by jimouris** [comment]
Sure.

[sum-client-array.cpp](https://github.com/jimouris/SPDZ-2/blob/sum-array/ExternalIO/sum-client-array.cpp) reads [data1.txt](https://github.com/jimouris/SPDZ-2/blob/sum-array/ExternalIO/data1.txt) (5 lines, numbers 1 to 5) and first sends `client-id, 5` and then `client-id, 1, 2, 3, 4, 5, finish-bit`.
Usage example: `./sum-client-array.x 789 2 ./ExternalIO/data1.txt 1`.

Here is the .mpc program [sum-array.mpc](https://github.com/jimouris/SPDZ-2/blob/sum-array/Programs/Source/sum-array.mpc). Line 47 never gets executed.

Finally, here is the updated [Makefile](https://github.com/jimouris/SPDZ-2/blob/sum-array/Makefile).

Thanks for your help.

**Comment by mkskeller** [comment]
I think you have to call `send_private_inputs` for every call of `sint.receive_from_client`, so if you have a loop in the MPC program, you will have to replicate that on the client side.

**Comment by jimouris** [comment]
Yes, that was the problem. Thanks for all your help!
