### ISSUE TITLE
Generating Random Numbers

### ISSUE THREAD

**Issue by ryandeng1** [bristolcrypto/SPDZ-2#68]
Is there any way to generate random numbers in a .mpc file? So far generate_random_triple() generates the same triples every time as in running the same mpc file multiple times will output the same numbers each time.

Also, as a side note, what does the size parameter do in generate_random_triple()?

**Comment by mkskeller** [comment]
I assume you mean `get_random_triple()`? There is `sint.get_random_int()` to get a random integer of a certain bit length, but that is actually less efficient than `get_random_triple()`. The size is used to construct three vector registers of the given size containing that many triples. Note however that using vector registers is poorly documented.

**Comment by ryandeng1** [comment]
Why is it that get_random_triple() produces the same triple when I run the program multiple times? Is there any way to produce different numbers each time such as python's random library?

**Comment by mkskeller** [comment]
Have you compiled with `-DINSECURE`? One effect of this is that it will reuse randomness when using `Player-Online.x`. Compiling without should change that.

**Comment by mkskeller** [comment]
In weaker security model it's easier to generate fresh randomness on the fly. SPDZ-2's successor [MP-SPDZ](https://github.com/n1analytics/MP-SPDZ) features honest-majority three-party computation with the same high-level language in `malicious-rep-field-party.x`.

**Comment by ryandeng1** [comment]
Ok, thanks!
