### ISSUE TITLE
Comparing sint, weird result

### ISSUE THREAD

**Issue by ryandeng1** [bristolcrypto/SPDZ-2#70]
So, I have the following mpc file.

a = sint.get_random_int(128)
b = sint.get_random_int(128)
print_ln("%s", (a < b).reveal())

I run ./compile.py -p 128 on this mpc file, and then run it. When I do, the comparison outputs a value not in {0, 1}. 

One example is I got a = -57913132484989201035523218661426488480
b = 19955784241450662315212052826534670829
a < b = -5104759913414732407 when it should be 1.
The prime field was modulo 172035116406933162231178957667602464769. 

Looking at the code in sint for comparison, I suspect it's related to overflowing the prime field, but not sure how.

A side note: I tried adding the line: program.set_bit_length(128) on the top of the .mpc program. However, when I run run-online.sh on this file, it throws an error saying: "Tape requires prime of bit length 170", even though I set the bit length to 128 in the program? The number required seems to always be 42 more than the length I initially set in the .mpc file (If I set it to 512, then when running, it will say tape requires prime of bit length 554).

Thanks!

**Comment by mkskeller** [comment]
Indeed, the length of the prime needs to be about 40 bits longer than the actual numbers for so-called statistical masking.

**Comment by ryandeng1** [comment]
Do you know why the comparison of 128 secret integers fails when I use -p 512 when compiling, and 512 bit primes as stated above in my original question? Thanks

**Comment by mkskeller** [comment]
The default configuration is for primes up to 128 bits only. You need to do the following for 512-bit primes: 
- Add the following line to CONFIG.mine: `MOD = -DMAX_MOD_SZ=8`
- Recompile: `make clean; make -j 8 online`
- Run setup: `Scripts/setup-online.sh <nparties> 512`

Then, add -lgp 512 when running Player-Online.x or run
Scripts/run-online.sh <program> 512

**Comment by ryandeng1** [comment]
Thank you! It works now. All I had to do was set the program bit length to the appropriate amount and the comparison now produces a valid result.
