### ISSUE TITLE
Malicious adversaries

### ISSUE THREAD

**Issue by prvsousa** [bristolcrypto/SPDZ-2#8]
This library provides security against active/malicious adversaries? And semi-honest/passive?

**Comment by rdragos** [comment]
SPDZ is secure against malicious adversaries (even with a majority of malicious parties).
For more details check the latest paper: http://eprint.iacr.org/2016/505.pdf

**Comment by patricia93sousa** [comment]
Only one question, a replay attack is possible in this? What you make to prevent this? There are any paper with this?
